version: '3.5'    
services:
  spotlight.en:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.en
    volumes:
       - spotlight-models:/opt/spotlight/models
    restart: unless-stopped   
    ports:
       - "0.0.0.0:2222:80"  
    command: /bin/spotlight.sh en
    
  spotlight.de:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.de
    volumes:
       - spotlight-models:/opt/spotlight/models
    restart: unless-stopped   
    ports:
       - "0.0.0.0:2223:80"  
    command: /bin/spotlight.sh de
    
  spotlight.pt:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.pt
    volumes:
       - spotlight-models:/opt/spotlight/models
    restart: unless-stopped   
    ports:
       - "0.0.0.0:2224:80"  
    command: /bin/spotlight.sh pt
  
volumes:
  spotlight-models:
    external: true
