version: '3.5'
services:
  spotlight.en:
    build: .
    image: spotlight-docker
    container_name: spotlight-en
    restart: unless-stopped
    ports:
      - "0.0.0.0:2222:80"
    command: /bin/spotlight_run.sh
